kind: Service
apiVersion: v1
metadata:
  name: jankenpon-client-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: jankenpon-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: frontend-port
