apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jankenpon-gateway
  name: jankenpon-gateway-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jankenpon-gateway-crb
  labels:
    app: jankenpon-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jankenpon-gateway-sa
  namespace: default
